### ISSUE TITLE
Improve the body type

### ISSUE THREAD

**Issue by kylef** [nestproject/Nest#2]
Body shouldn't simply be a string, it should become some form of stream or generator. So a client can stream large files. It should also not be tied to any particular encoding type. Swift strings are Unicode internally and this would prevent using other types (unless the server converted).

**Comment by davidcelis** [comment]
I also question the specification that the body can be `nil`. Is there a reason to prefer a nullable body than to make it an empty string for empty bodies?

**Comment by rparada** [comment]
I agree with both comments. It is important to be able to stream content to the client, such as when a large file is generated and you want to send it in the response. Reading the entire file into memory would be inefficient. Also, some content may be binary content. Not all responses are Strings.

**Comment by kylef** [comment]
Moved this to [NEP 2](https://github.com/nestproject/neps/blob/master/draft/0002-streamable-bodies.md).
