### ISSUE TITLE
Support byte outputs

### ISSUE THREAD

**Issue by Bouke** [nestproject/Nest#9]
The current spec only allows String responses. However what if you'd want to output a binary file from disk? So I think support for byte outputs would be welcome as well. (`UInt8`?)

**Comment by kylef** [comment]
Agreed, this should become a stream of bytes. This is mentioned in #2 also.

**Comment by kylef** [comment]
Moved this to [NEP 2](https://github.com/nestproject/neps/blob/master/draft/0002-streamable-bodies.md).
